services:
  postgres:
    image: postgres:16
    container_name: retail-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: productsdb
      POSTGRES_USER: products
      POSTGRES_PASSWORD: products
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U products -d productsdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  mongo:
    image: mongo:7
    container_name: retail-mongo
    ports:
      - "27017:27017"

  kafka:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.3
    container_name: retail-kafka
    command: >
      redpanda start --overprovisioned --smp 1 --memory 1G --mode dev
    ports:
      - "9092:9092"
