spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productsdb
    username: products
    password: products
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: products-service

server:
  port: 8081

springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger-ui
management:
  endpoints.web.exposure.include: health,info,metrics
